name: Publish to npm

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish package
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'

      - name: Enable Corepack (Yarn)
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Determine package and version
        id: pkg
        shell: bash
        run: |
          NAME=$(node -p "require('./package.json').name")
          VERSION=$(node -p "require('./package.json').version")
          echo "name=$NAME" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if version already exists on npm
        id: exists
        shell: bash
        env:
          NAME: ${{ steps.pkg.outputs.name }}
          VERSION: ${{ steps.pkg.outputs.version }}
        run: |
          if npm view "$NAME@$VERSION" version > /dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "Version $NAME@$VERSION already exists. Skipping publish."
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "Version $NAME@$VERSION does not exist. Will publish."
          fi

      - name: Publish to npm
        if: steps.exists.outputs.exists == 'false'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish --access public


